export const constants = {
  APP_TITLE: "ApplyNinja.ai",
  PRICE_CV_SUGGESTIONS: 10,
  PRICE_COMPANY_INSIGHTS: 10,
  PRICE_ESTIMATED_SALARY: 10,
  PRICE_COVER_LETTER: 10,
  PRICE_INTERVIEW_QUESTIONS: 20,
  LIMIT_JOBS_FREE: 5,
  LIMIT_JOBS_APPRENTICE: 100,
  LIMIT_JOBS_NINJA: 200,
  SUBSCRIPTION: {
    TIERS: {
      FREE: {
        name: "FREE",
        price: 0,
        monthlyTokens: 0,
        popular: false,
        priceId: undefined,
        description: "For trying out our features",
        features: {
          included: [
            "<strong>50</strong> starting tokens",
            "<strong>5</strong> job limit",
            "CV suggestions",
            "Cover letter generation",
            "Company insights",
            "Salary insights",
            "Basic AI model",
          ],
          excluded: [
            "<strong>Interview preparation</strong>",
            "<strong>Advanced AI model</strong>",
          ],
        },
      },
      APPRENTICE: {
        name: "APPRENTICE",
        price: 19,
        description: "For serious job seekers",
        monthlyTokens: 3500,
        popular: false,
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_APPRENTICE!,
        features: {
          included: [
            "<strong>3500</strong> monthly tokens",
            "<strong>100</strong> job limit",
            "CV suggestions",
            "Cover letter generation",
            "Company insights",
            "Salary insights",
            "<strong>Interview preparation</strong>",
            "<strong>Advanced AI model</strong>",
          ],
          excluded: [],
        },
      },
      NINJA: {
        name: "NINJA",
        price: 29,
        monthlyTokens: 7000,
        description: "For power users and frequent job changers",
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NINJA!,
        popular: true,
        features: {
          included: [
            "<strong>7000</strong> monthly tokens",
            "<strong>200</strong> job limit",
            "CV suggestions",
            "Cover letter generation",
            "Company insights",
            "Salary insights",
            "<strong>Interview preparation</strong>",
            "<strong>Advanced AI model</strong>",
          ],
          excluded: [],
        },
      },
    },
  },
};
